# Generated by Django 3.0.3 on 2020-03-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_tittle', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField(max_length=5)),
                ('stock', models.IntegerField(max_length=3)),
            ],
        ),
    ]
