# Generated by Django 3.0.3 on 2020-03-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20200311_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regisvendor',
        ),
    ]
