# Generated by Django 3.0.3 on 2020-03-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_delete_regisvendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
