# Generated by Django 3.0.3 on 2020-03-14 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vendor', '0011_productdetails_ven_id'),
        ('Store', '0004_delete_productdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendor.ProductDetails')),
            ],
        ),
    ]
