# Generated by Django 3.0.3 on 2020-03-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20200314_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='imag',
        ),
        migrations.AddField(
            model_name='cart',
            name='ima',
            field=models.ImageField(default='', upload_to='Store/images'),
        ),
    ]
