# Generated by Django 3.0.3 on 2020-03-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_auto_20200314_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ima',
        ),
    ]
