# Generated by Django 3.0.3 on 2020-03-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0011_productdetails_ven_id'),
        ('Store', '0008_remove_cart_ima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='c_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Vendor.ProductDetails'),
        ),
    ]
