# Generated by Django 3.0.3 on 2020-03-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_auto_20200315_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
